# Create this manifest using kubectl to deploy
# the Calico policy controller on Kubernetes.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calico-policy
  namespace: kube-system
  labels:
    k8s-app: calico-policy
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: calico-policy
  template:
    metadata:
      labels:
        k8s-app: calico-policy
        kubernetes.io/cluster-service: "true"
    spec:
      hostNetwork: true
      containers:
        - name: calico-policy
          image: calico/kube-policy-controller:latest
          env:
            # Configure the policy controller with the location of 
            # your etcd cluster.
            - name: ETCD_ENDPOINTS
              value: "http://cld000001:4001,http://cld000002:4001,http://cld000003:4001"
            - name: K8S_API
              value: "https://kubernetes.default:443"
            - name: CONFIGURE_ETC_HOSTS
              value: "true"
