kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ig-grafana
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      k8s-app: influxGrafana
      ig-comp: grafana
